name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: Switch node version
        uses: actions/setup-node@v1
        with:
          node-version: "10.16.3"
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Prepare npm token
        run: npm set //registry.npmjs.org/:_authToken ${{ secret.NPM_TOKEN }}
      - name: Publish to npm
        run: npm publish .
